server:
  port: 9002

#database
spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/microservice?useUnicode=yes&characterEncoding=UTF-8&serverTimezone=Asia/Bangkok
    username: root
    password: 1234

jwt:
  secret: BvPHGM8C0ia4uOuxxqPD5DTbWC9F9TWvPStp3pb7ARo0oK2mJ3pd3YG4lxA9i8bj6OTbadwezxgeEByY
  expiration: 86400
